apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: watch-diff
spec:
  version: "v0.0.1"
  homepage: https://github.com/alexmt/kubectl-watch-diff
  shortDescription: "Watches the changes in the k8s resource and prints the diff."
  description: |
    Watches the the k8s resource with the given name.
    Prints the diff of the resource when it changes.
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
      - key: "arch"
        operator: "In"
        values:
        - amd64
    uri: https://github.com/achanda/kubectl-restart/archive/v0.0.3.zip
    # 'sha256' is the sha256sum of the url (archive file) above
    sha256: d7079b79bf4e10e55ded435a2e862efe310e019b6c306a8ff04191238ef4b2b4
    # 'files' lists which files should be extracted out from downloaded archive
    files:
    - from: "kubectl-restart-*/restart.sh"
      to: "./restart.sh"
    - from: "LICENSE"
      to: "."
    # 'bin' specifies the path to the the plugin executable among extracted files
    bin: restart.sh