name: Release binaries
on:
  release:
    types:
      - published
jobs:
  build-binaries:
    permissions:
      contents: write
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - run: |
          mkdir dist
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o dist/watchdiff ./main.go
          cp LICENSE dist/LICENSE
          zip watchdiff-${{ matrix.os }}-${{ matrix.arch }}.zip dist/*
          sha256sum watchdiff-${{ matrix.os }}-${{ matrix.arch }}.zip
      - run: gh release upload ${{ github.ref_name }} watchdiff-${{ matrix.os }}-${{ matrix.arch }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
